version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      -  pip install pre-commit cloudformation-cli-java-plugin
      -  pip install --upgrade 'six==1.15.0'
      -  pip install --upgrade 'pyyaml==6.0'
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR/common"
      - mvn clean verify install --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-amplify-app"
      - mvn clean verify -X --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-amplify-branch"
      - mvn clean verify -X --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-amplify-domain"
      - mvn clean verify -X --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-amplify-app/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-amplify-branch/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-amplify-domain/rpdk.log"
